# Generated by Django 2.0.5 on 2018-05-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecommand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='douBanId',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='doubanRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='doubanRatingPeron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='doubanSummary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='seriesTitle',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='systemNumber',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
