# Generated by Django 2.0.5 on 2018-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecommand', '0002_auto_20180516_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='catalog',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='douBanId',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='doubanRating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='doubanRatingPeron',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='doubanSummary',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='index',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishYear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='seriesTitle',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='systemNumber',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
