# Generated by Django 2.0.5 on 2018-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecommand', '0005_auto_20180516_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
