# Generated by Django 2.0.5 on 2018-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRecommand', '0008_auto_20180516_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
